version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

